# Basic DJI Avata 2 Video Processor Configuration
# Copy this to ~/.dji-processor/config.yml or ./dji-config.yml

# === ESSENTIAL SETTINGS ===
source_directory: "./input"
output_directory: "./output"
lut_file: "./luts/Avata2.cube"

# Video quality: draft, standard, high, professional
quality_preset: "standard"

# Parallel jobs: auto, or number (1-8)
parallel_jobs: "auto"

# === BASIC FEATURES ===
# Skip files that already exist
skip_existing: true

# Preserve original file timestamps
preserve_timestamps: true

# Send notification when done
macos_notifications: true

# Play sound when complete
completion_sound: true