# Lightweight DJI Avata 2 Video Processor Configuration
# Optimized for low system impact and web sharing

# === PATHS ===
source_directory: "/Users/username/Movies/DJI/source"
output_directory: "/Users/username/Movies/DJI/web"
lut_file: "/Users/username/Movies/DJI/Avata2.cube"

# === LIGHTWEIGHT SETTINGS ===
# Lower quality for web sharing
quality_preset: "medium"

# Reduced parallel jobs to minimize system impact
parallel_jobs: 2

# === EFFICIENCY FEATURES ===
# Skip existing files to save time
skip_existing: true

# No backup (save space)
auto_backup: false

# No date organization (simpler structure)
organize_by_date: false

# Basic metadata only
preserve_metadata: false
preserve_timestamps: true
add_processing_metadata: false

# === FILE FILTERING ===
# Skip very small files (likely corrupted)
min_file_size: 5

# Skip very large files (save processing time)
max_file_size: 5

# Basic file types only
file_extensions:
  - "mp4"
  - "MP4"

# === MINIMAL MONITORING ===
verbose_logging: false
log_file: ""
keep_job_logs: false
macos_notifications: true
completion_sound: false

# === CONSERVATIVE PERFORMANCE ===
max_cpu_usage: 70
thermal_protection: true