# Professional DJI Avata 2 Video Processor Configuration
# High-end settings for professional video production

# === PATHS ===
source_directory: "./input"
output_directory: "./output"
lut_file: "./luts/Avata2.cube"

# === QUALITY SETTINGS ===
quality_preset: "high"
parallel_jobs: 4

# === PROFESSIONAL FEATURES ===
# Backup originals before processing
auto_backup: true
backup_directory: "./backup"

# Organize output by shoot date
organize_by_date: true
date_format: "%Y-%m-%d"

# Preserve all metadata
preserve_metadata: true
preserve_timestamps: true

# Add processing metadata for tracking
add_processing_metadata: true

# === ADVANCED ENCODING ===
# Force specific encoder for consistency
force_encoder: "h264_videotoolbox"

# Custom FFmpeg arguments for professional quality
custom_ffmpeg_args: "-preset slow -tune film"

# === FILE HANDLING ===
# Process larger files (professional cameras)
min_file_size: 50
max_file_size: 20

# Support multiple formats
file_extensions:
  - "mp4"
  - "MP4"
  - "mov"
  - "MOV"

# === MONITORING ===
verbose_logging: true
log_file: "/Users/username/Videos/DJI/processing.log"
keep_job_logs: true
macos_notifications: true
completion_sound: true

# === PERFORMANCE ===
max_cpu_usage: 85
thermal_protection: true